run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    - exhaustruct
    - exhaustivestruct
    - deadcode # deprecated
    - depguard
    - errchkjson
    - forbidigo
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - goerr113
    - gofumpt
    - golint # deprecated
    - gomnd
    - gosmopolitan
    - ifshort # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - musttag
    - nosnakecase # deprecated
    - paralleltest
    - revive
    - scopelint # deprecated
    - structcheck # deprecated
    - tagliatelle
    - varcheck # deprecated
    - varnamelen
    - wrapcheck
    - wsl