run:
  timeout: 5m

# https://golangci-lint.run/usage/linters/
linters:
  enable-all: true
  disable:
    - depguard
    - dupl
    - execinquery # deprecated
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gomnd # deprecated
    - interfacebloat
    - ireturn
    - mnd
    - varnamelen

linters-settings:
  cyclop:
    max-complexity: 15
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/lostsnow/keqing)
  gofumpt:
    module-path: github.com/lostsnow/keqing
  goimports:
    local-prefixes: github.com/lostsnow/keqing
  nestif:
    min-complexity: 10
