// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Chat is the predicate function for chat builders.
type Chat func(*sql.Selector)

// ChatOption is the predicate function for chatoption builders.
type ChatOption func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
