// Code generated by ent, DO NOT EDIT.

package entity

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lostsnow/keqing/pkg/entity/chatoption"
	"github.com/lostsnow/keqing/pkg/entity/predicate"
)

// ChatOptionQuery is the builder for querying ChatOption entities.
type ChatOptionQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.ChatOption
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChatOptionQuery builder.
func (coq *ChatOptionQuery) Where(ps ...predicate.ChatOption) *ChatOptionQuery {
	coq.predicates = append(coq.predicates, ps...)
	return coq
}

// Limit the number of records to be returned by this query.
func (coq *ChatOptionQuery) Limit(limit int) *ChatOptionQuery {
	coq.ctx.Limit = &limit
	return coq
}

// Offset to start from.
func (coq *ChatOptionQuery) Offset(offset int) *ChatOptionQuery {
	coq.ctx.Offset = &offset
	return coq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (coq *ChatOptionQuery) Unique(unique bool) *ChatOptionQuery {
	coq.ctx.Unique = &unique
	return coq
}

// Order specifies how the records should be ordered.
func (coq *ChatOptionQuery) Order(o ...OrderFunc) *ChatOptionQuery {
	coq.order = append(coq.order, o...)
	return coq
}

// First returns the first ChatOption entity from the query.
// Returns a *NotFoundError when no ChatOption was found.
func (coq *ChatOptionQuery) First(ctx context.Context) (*ChatOption, error) {
	nodes, err := coq.Limit(1).All(setContextOp(ctx, coq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{chatoption.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (coq *ChatOptionQuery) FirstX(ctx context.Context) *ChatOption {
	node, err := coq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChatOption ID from the query.
// Returns a *NotFoundError when no ChatOption ID was found.
func (coq *ChatOptionQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = coq.Limit(1).IDs(setContextOp(ctx, coq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{chatoption.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (coq *ChatOptionQuery) FirstIDX(ctx context.Context) int64 {
	id, err := coq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChatOption entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChatOption entity is found.
// Returns a *NotFoundError when no ChatOption entities are found.
func (coq *ChatOptionQuery) Only(ctx context.Context) (*ChatOption, error) {
	nodes, err := coq.Limit(2).All(setContextOp(ctx, coq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{chatoption.Label}
	default:
		return nil, &NotSingularError{chatoption.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (coq *ChatOptionQuery) OnlyX(ctx context.Context) *ChatOption {
	node, err := coq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChatOption ID in the query.
// Returns a *NotSingularError when more than one ChatOption ID is found.
// Returns a *NotFoundError when no entities are found.
func (coq *ChatOptionQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = coq.Limit(2).IDs(setContextOp(ctx, coq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{chatoption.Label}
	default:
		err = &NotSingularError{chatoption.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (coq *ChatOptionQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := coq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChatOptions.
func (coq *ChatOptionQuery) All(ctx context.Context) ([]*ChatOption, error) {
	ctx = setContextOp(ctx, coq.ctx, "All")
	if err := coq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChatOption, *ChatOptionQuery]()
	return withInterceptors[[]*ChatOption](ctx, coq, qr, coq.inters)
}

// AllX is like All, but panics if an error occurs.
func (coq *ChatOptionQuery) AllX(ctx context.Context) []*ChatOption {
	nodes, err := coq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChatOption IDs.
func (coq *ChatOptionQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if coq.ctx.Unique == nil && coq.path != nil {
		coq.Unique(true)
	}
	ctx = setContextOp(ctx, coq.ctx, "IDs")
	if err = coq.Select(chatoption.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (coq *ChatOptionQuery) IDsX(ctx context.Context) []int64 {
	ids, err := coq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (coq *ChatOptionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, coq.ctx, "Count")
	if err := coq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, coq, querierCount[*ChatOptionQuery](), coq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (coq *ChatOptionQuery) CountX(ctx context.Context) int {
	count, err := coq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (coq *ChatOptionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, coq.ctx, "Exist")
	switch _, err := coq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("entity: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (coq *ChatOptionQuery) ExistX(ctx context.Context) bool {
	exist, err := coq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChatOptionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (coq *ChatOptionQuery) Clone() *ChatOptionQuery {
	if coq == nil {
		return nil
	}
	return &ChatOptionQuery{
		config:     coq.config,
		ctx:        coq.ctx.Clone(),
		order:      append([]OrderFunc{}, coq.order...),
		inters:     append([]Interceptor{}, coq.inters...),
		predicates: append([]predicate.ChatOption{}, coq.predicates...),
		// clone intermediate query.
		sql:  coq.sql.Clone(),
		path: coq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ChatID int64 `json:"chat_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChatOption.Query().
//		GroupBy(chatoption.FieldChatID).
//		Aggregate(entity.Count()).
//		Scan(ctx, &v)
func (coq *ChatOptionQuery) GroupBy(field string, fields ...string) *ChatOptionGroupBy {
	coq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChatOptionGroupBy{build: coq}
	grbuild.flds = &coq.ctx.Fields
	grbuild.label = chatoption.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ChatID int64 `json:"chat_id,omitempty"`
//	}
//
//	client.ChatOption.Query().
//		Select(chatoption.FieldChatID).
//		Scan(ctx, &v)
func (coq *ChatOptionQuery) Select(fields ...string) *ChatOptionSelect {
	coq.ctx.Fields = append(coq.ctx.Fields, fields...)
	sbuild := &ChatOptionSelect{ChatOptionQuery: coq}
	sbuild.label = chatoption.Label
	sbuild.flds, sbuild.scan = &coq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChatOptionSelect configured with the given aggregations.
func (coq *ChatOptionQuery) Aggregate(fns ...AggregateFunc) *ChatOptionSelect {
	return coq.Select().Aggregate(fns...)
}

func (coq *ChatOptionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range coq.inters {
		if inter == nil {
			return fmt.Errorf("entity: uninitialized interceptor (forgotten import entity/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, coq); err != nil {
				return err
			}
		}
	}
	for _, f := range coq.ctx.Fields {
		if !chatoption.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("entity: invalid field %q for query", f)}
		}
	}
	if coq.path != nil {
		prev, err := coq.path(ctx)
		if err != nil {
			return err
		}
		coq.sql = prev
	}
	return nil
}

func (coq *ChatOptionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChatOption, error) {
	var (
		nodes = []*ChatOption{}
		_spec = coq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChatOption).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChatOption{config: coq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, coq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (coq *ChatOptionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := coq.querySpec()
	_spec.Node.Columns = coq.ctx.Fields
	if len(coq.ctx.Fields) > 0 {
		_spec.Unique = coq.ctx.Unique != nil && *coq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, coq.driver, _spec)
}

func (coq *ChatOptionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(chatoption.Table, chatoption.Columns, sqlgraph.NewFieldSpec(chatoption.FieldID, field.TypeInt64))
	_spec.From = coq.sql
	if unique := coq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if coq.path != nil {
		_spec.Unique = true
	}
	if fields := coq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatoption.FieldID)
		for i := range fields {
			if fields[i] != chatoption.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := coq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := coq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := coq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := coq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (coq *ChatOptionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(coq.driver.Dialect())
	t1 := builder.Table(chatoption.Table)
	columns := coq.ctx.Fields
	if len(columns) == 0 {
		columns = chatoption.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if coq.sql != nil {
		selector = coq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if coq.ctx.Unique != nil && *coq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range coq.predicates {
		p(selector)
	}
	for _, p := range coq.order {
		p(selector)
	}
	if offset := coq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := coq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChatOptionGroupBy is the group-by builder for ChatOption entities.
type ChatOptionGroupBy struct {
	selector
	build *ChatOptionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cogb *ChatOptionGroupBy) Aggregate(fns ...AggregateFunc) *ChatOptionGroupBy {
	cogb.fns = append(cogb.fns, fns...)
	return cogb
}

// Scan applies the selector query and scans the result into the given value.
func (cogb *ChatOptionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cogb.build.ctx, "GroupBy")
	if err := cogb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatOptionQuery, *ChatOptionGroupBy](ctx, cogb.build, cogb, cogb.build.inters, v)
}

func (cogb *ChatOptionGroupBy) sqlScan(ctx context.Context, root *ChatOptionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cogb.fns))
	for _, fn := range cogb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cogb.flds)+len(cogb.fns))
		for _, f := range *cogb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cogb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cogb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChatOptionSelect is the builder for selecting fields of ChatOption entities.
type ChatOptionSelect struct {
	*ChatOptionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cos *ChatOptionSelect) Aggregate(fns ...AggregateFunc) *ChatOptionSelect {
	cos.fns = append(cos.fns, fns...)
	return cos
}

// Scan applies the selector query and scans the result into the given value.
func (cos *ChatOptionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cos.ctx, "Select")
	if err := cos.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatOptionQuery, *ChatOptionSelect](ctx, cos.ChatOptionQuery, cos, cos.inters, v)
}

func (cos *ChatOptionSelect) sqlScan(ctx context.Context, root *ChatOptionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cos.fns))
	for _, fn := range cos.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cos.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cos.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
