// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package i18n

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US":   &dictionary{index: en_USIndex, data: en_USData},
		"zh_Hans": &dictionary{index: zh_HansIndex, data: zh_HansData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"A Thousand Floating Dreams":  36,
	"Akuoumaru":                   37,
	"Albedo":                      38,
	"Alhaitham":                   39,
	"Alley Hunter":                40,
	"Aloy":                        41,
	"Amber":                       42,
	"Amenoma Kageuchi":            43,
	"Amos Bow":                    44,
	"Anemo":                       31,
	"Apprentices Notes":           45,
	"Aqua Simulacra":              46,
	"Aquila Favonia":              47,
	"Arataki Itto":                48,
	"Authentication successfully": 28,
	"Baizhu":                      49,
	"Barbara":                     50,
	"Beacon of the Reed Sea":      51,
	"Beginners Protector":         52,
	"Beidou":                      53,
	"Bennett":                     54,
	"Black Tassel":                55,
	"Blackcliff Agate":            56,
	"Blackcliff Longsword":        57,
	"Blackcliff Pole":             58,
	"Blackcliff Slasher":          59,
	"Blackcliff Warbow":           60,
	"Bloodtainted Greatsword":     61,
	"Bow":                         264,
	"Calamity Queller":            62,
	"Candace":                     63,
	"Catalyst":                    263,
	"Chongyun":                    64,
	"Cinnabar Spindle":            65,
	"Claymore":                    261,
	"Collei":                      66,
	"Compound Bow":                67,
	"Cookie token fetch failed, please try again": 20,
	"Cool Steel":           68,
	"Crescent Pike":        69,
	"Cryo":                 34,
	"Cut to the chase":     1,
	"Cyno":                 70,
	"Dark Iron Sword":      71,
	"Deathmatch":           72,
	"Debate Club":          73,
	"Dehya":                74,
	"Dendro":               33,
	"Diluc":                75,
	"Diona":                76,
	"Dodoco Tales":         77,
	"Dori":                 78,
	"Dragons Bane":         79,
	"Dragonspine Spear":    80,
	"Dull Blade":           81,
	"Electro":              32,
	"Elegy for the End":    82,
	"Emerald Orb":          83,
	"End of the Line":      84,
	"Engulfing Lightning":  85,
	"Eula":                 86,
	"Everlasting Moonglow": 87,
	"Eye of Perception":    88,
	"Fading Twilight":      89,
	"Faruzan":              90,
	"Favonius Codex":       91,
	"Favonius Greatsword":  92,
	"Favonius Lance":       93,
	"Favonius Sword":       94,
	"Favonius Warbow":      95,
	"Ferrous Shadow":       96,
	"Festering Desire":     97,
	"Fetch QR code failed": 8,
	"Fillet Blade":         98,
	"Fischl":               99,
	"Forest Regalia":       100,
	"Freedom-Sworn":        101,
	"Friday":               15,
	"Frostbearer":          102,
	"Fruit of Fulfillment": 103,
	"Game token parse failed, please try again": 19,
	"Ganyu":                    104,
	"Generate QR code failed":  9,
	"Geo":                      35,
	"Gorou":                    105,
	"Hakushin Ring":            106,
	"Halberd":                  107,
	"Hamayumi":                 108,
	"Haran Geppaku Futsu":      109,
	"Harbinger of Dawn":        110,
	"Hu Tao":                   111,
	"Hunters Bow":              112,
	"Hunters Path":             113,
	"Hydro":                    30,
	"Iron Point":               114,
	"Iron Sting":               115,
	"Jadefalls Splendor":       116,
	"Jean":                     117,
	"Kaedehara Kazuha":         118,
	"Kaeya":                    119,
	"Kagotsurube Isshin":       120,
	"Kaguras Verity":           121,
	"Kamisato Ayaka":           122,
	"Kamisato Ayato":           123,
	"Katsuragikiri Nagamasa":   124,
	"Kaveh":                    125,
	"Keqing":                   126,
	"Key of Khaj Nisut":        127,
	"Kings Squire":             128,
	"Kirara":                   129,
	"Kitain Cross Spear":       130,
	"Klee":                     131,
	"Kujou Sara":               132,
	"Kuki Shinobu":             133,
	"Layla":                    134,
	"Light of Foliar Incision": 135,
	"Lions Roar":               136,
	"Lisa":                     137,
	"Lithic Blade":             138,
	"Lithic Spear":             139,
	"Login failed or QR code expired, please try again": 18,
	"Lost Prayer to the Sacred Winds":                   140,
	"Luxurious Sea Lord":                                141,
	"Magic Guide":                                       142,
	"Mailed Flower":                                     143,
	"Makhaira Aquamarine":                               144,
	"Mappa Mare":                                        145,
	"Memory of Dust":                                    146,
	"Messenger":                                         147,
	"Mika":                                              148,
	"Missive Windspear":                                 149,
	"Mistsplitter Reforged":                             150,
	"Mitternachts Waltz":                                151,
	"Mona":                                              152,
	"Monday":                                            12,
	"Moonpiercer":                                       153,
	"Mouuns Moon":                                       154,
	"Nahida":                                            155,
	"Nilou":                                             156,
	"Ningguang":                                         157,
	"No game role found, please send command /game_refresh_role to refresh": 4,
	"No such character": 0,
	"Noelle":            158,
	"Not yet implemented, send command %s instead": 2,
	"Oathsworn Eye":      159,
	"Otherworldly Story": 160,
	"Please scan the QR code with the miyoushe App": 10,
	"Please send me a private chat message":         5,
	"Pocket Grimoire":                               161,
	"Polar Star":                                    162,
	"Polearm":                                       262,
	"Predator":                                      163,
	"Primordial Jade Cutter":                        164,
	"Primordial Jade Winged Spear":                  165,
	"Prototype Amber":                               166,
	"Prototype Archaic":                             167,
	"Prototype Crescent":                            168,
	"Prototype Rancour":                             169,
	"Prototype Starglitter":                         170,
	"Pyro":                                          29,
	"QR code login is being checked":                6,
	"Qiqi":                                          171,
	"Query game role failed":                        3,
	"Raiden Shogun":                                 172,
	"Rainslasher":                                   173,
	"Raven Bow":                                     174,
	"Razor":                                         175,
	"Recurve Bow":                                   176,
	"Redhorn Stonethresher":                         177,
	"Rosaria":                                       178,
	"Royal Bow":                                     179,
	"Royal Greatsword":                              180,
	"Royal Grimoire":                                181,
	"Royal Longsword":                               182,
	"Royal Spear":                                   183,
	"Rust":                                          184,
	"Sacrificial Bow":                               185,
	"Sacrificial Fragments":                         186,
	"Sacrificial Greatsword":                        187,
	"Sacrificial Sword":                             188,
	"Sangonomiya Kokomi":                            189,
	"Sapwood Blade":                                 190,
	"Saturday":                                      17,
	"Sayu":                                          191,
	"Seasoned Hunters Bow":                          192,
	"Serpent Spine":                                 193,
	"Sharpshooters Oath":                            194,
	"Shenhe":                                        195,
	"Shikanoin Heizou":                              196,
	"Silver Sword":                                  197,
	"Skyrider Greatsword":                           198,
	"Skyrider Sword":                                199,
	"Skyward Atlas":                                 200,
	"Skyward Blade":                                 201,
	"Skyward Harp":                                  202,
	"Skyward Pride":                                 203,
	"Skyward Spine":                                 204,
	"Slingshot":                                     205,
	"Snow Tombed Starsilver":                        206,
	"Solar Pearl":                                   207,
	"Song of Broken Pines":                          208,
	"Staff of Homa":                                 209,
	"Staff of the Scarlet Sands":                    210,
	"Sucrose":                                       211,
	"Summit Shaper":                                 212,
	"Sword":                                         260,
	"Sword of Descension":                           213,
	"Tartaglia":                                     214,
	"The Alley Flash":                               215,
	"The Bell":                                      216,
	"The Black Sword":                               217,
	"The Catch":                                     218,
	"The Flute":                                     219,
	"The Stringless":                                220,
	"The Unforged":                                  221,
	"The Viridescent Hunt":                          222,
	"The Widsith":                                   223,
	"The account has not been bound to Genshin Impact, please confirm that the account is correct":       25,
	"The account is not yet bound to any game, please make sure the account of scanning code is correct": 24,
	"Thoma":                              224,
	"Thrilling Tales of Dragon Slayers":  225,
	"Thundering Pulse":                   226,
	"Thursday":                           13,
	"Tighnari":                           227,
	"Toukabou Shigure":                   228,
	"Traveler Anemo":                     229,
	"Traveler Dendro":                    230,
	"Traveler Electro":                   231,
	"Traveler Geo":                       232,
	"Travelers Handy Sword":              233,
	"Tuesday":                            14,
	"Tulaytullahs Remembrance":           234,
	"Twin Nephrite":                      235,
	"Upsert game account failed":         22,
	"Upsert game roles attribute failed": 27,
	"Upsert game roles failed":           26,
	"Upsert user failed":                 7,
	"Venti":                              236,
	"Vortex Vanquisher":                  237,
	"Wanderer":                           238,
	"Wandering Evenstar":                 239,
	"Waster Greatsword":                  240,
	"Wavebreakers Fin":                   241,
	"Wednesday":                          16,
	"What are you looking for, it does not exist": 11,
	"White Iron Greatsword":                       242,
	"White Tassel":                                243,
	"Whiteblind":                                  244,
	"Windblume Ode":                               245,
	"Wine and Song":                               246,
	"Wolfs Gravestone":                            247,
	"Xiangling":                                   248,
	"Xiao":                                        249,
	"Xingqiu":                                     250,
	"Xinyan":                                      251,
	"Xiphos Moonlight":                            252,
	"Yae Miko":                                    253,
	"Yanfei":                                      254,
	"Yaoyao":                                      255,
	"Yelan":                                       256,
	"Yoimiya":                                     257,
	"Yun Jin":                                     258,
	"Zhongli":                                     259,
	"fetch game record failed, please try again": 23,
	"stoken fetch failed, please try again":      21,
}

var en_USIndex = []uint32{ // 266 elements
	// Entry 0 - 1F
	0x00000000, 0x00000012, 0x00000023, 0x00000053,
	0x0000006a, 0x000000b0, 0x000000d6, 0x000000f5,
	0x00000108, 0x0000011d, 0x00000135, 0x00000163,
	0x0000018f, 0x00000196, 0x0000019f, 0x000001a7,
	0x000001ae, 0x000001b8, 0x000001c1, 0x000001f3,
	0x0000021d, 0x00000249, 0x0000026f, 0x0000028a,
	0x000002b5, 0x00000318, 0x00000375, 0x0000038e,
	0x000003b1, 0x000003cd, 0x000003d2, 0x000003d8,
	// Entry 20 - 3F
	0x000003de, 0x000003e6, 0x000003ed, 0x000003f2,
	0x000003f6, 0x00000411, 0x0000041b, 0x00000422,
	0x0000042c, 0x00000439, 0x0000043e, 0x00000444,
	0x00000455, 0x0000045e, 0x00000470, 0x0000047f,
	0x0000048e, 0x0000049b, 0x000004a2, 0x000004aa,
	0x000004c1, 0x000004d5, 0x000004dc, 0x000004e4,
	0x000004f1, 0x00000502, 0x00000517, 0x00000527,
	0x0000053a, 0x0000054c, 0x00000564, 0x00000575,
	// Entry 40 - 5F
	0x0000057d, 0x00000586, 0x00000597, 0x0000059e,
	0x000005ab, 0x000005b6, 0x000005c4, 0x000005c9,
	0x000005d9, 0x000005e4, 0x000005f0, 0x000005f6,
	0x000005fc, 0x00000602, 0x0000060f, 0x00000614,
	0x00000621, 0x00000633, 0x0000063e, 0x00000650,
	0x0000065c, 0x0000066c, 0x00000680, 0x00000685,
	0x0000069a, 0x000006ac, 0x000006bc, 0x000006c4,
	0x000006d3, 0x000006e7, 0x000006f6, 0x00000705,
	// Entry 60 - 7F
	0x00000715, 0x00000724, 0x00000735, 0x00000742,
	0x00000749, 0x00000758, 0x00000766, 0x00000772,
	0x00000787, 0x0000078d, 0x00000793, 0x000007a1,
	0x000007a9, 0x000007b2, 0x000007c6, 0x000007d8,
	0x000007df, 0x000007eb, 0x000007f8, 0x00000803,
	0x0000080e, 0x00000821, 0x00000826, 0x00000837,
	0x0000083d, 0x00000850, 0x0000085f, 0x0000086e,
	0x0000087d, 0x00000894, 0x0000089a, 0x000008a1,
	// Entry 80 - 9F
	0x000008b3, 0x000008c0, 0x000008c7, 0x000008da,
	0x000008df, 0x000008ea, 0x000008f7, 0x000008fd,
	0x00000916, 0x00000921, 0x00000926, 0x00000933,
	0x00000940, 0x00000960, 0x00000973, 0x0000097f,
	0x0000098d, 0x000009a1, 0x000009ac, 0x000009bb,
	0x000009c5, 0x000009ca, 0x000009dc, 0x000009f2,
	0x00000a05, 0x00000a0a, 0x00000a16, 0x00000a22,
	0x00000a29, 0x00000a2f, 0x00000a39, 0x00000a40,
	// Entry A0 - BF
	0x00000a4e, 0x00000a61, 0x00000a71, 0x00000a7c,
	0x00000a85, 0x00000a9c, 0x00000ab9, 0x00000ac9,
	0x00000adb, 0x00000aee, 0x00000b00, 0x00000b16,
	0x00000b1b, 0x00000b29, 0x00000b35, 0x00000b3f,
	0x00000b45, 0x00000b51, 0x00000b67, 0x00000b6f,
	0x00000b79, 0x00000b8a, 0x00000b99, 0x00000ba9,
	0x00000bb5, 0x00000bba, 0x00000bca, 0x00000be0,
	0x00000bf7, 0x00000c09, 0x00000c1c, 0x00000c2a,
	// Entry C0 - DF
	0x00000c2f, 0x00000c44, 0x00000c52, 0x00000c65,
	0x00000c6c, 0x00000c7d, 0x00000c8a, 0x00000c9e,
	0x00000cad, 0x00000cbb, 0x00000cc9, 0x00000cd6,
	0x00000ce4, 0x00000cf2, 0x00000cfc, 0x00000d13,
	0x00000d1f, 0x00000d34, 0x00000d42, 0x00000d5d,
	0x00000d65, 0x00000d73, 0x00000d87, 0x00000d91,
	0x00000da1, 0x00000daa, 0x00000dba, 0x00000dc4,
	0x00000dce, 0x00000ddd, 0x00000dea, 0x00000dff,
	// Entry E0 - FF
	0x00000e0b, 0x00000e11, 0x00000e33, 0x00000e44,
	0x00000e4d, 0x00000e5e, 0x00000e6d, 0x00000e7d,
	0x00000e8e, 0x00000e9b, 0x00000eb1, 0x00000eca,
	0x00000ed8, 0x00000ede, 0x00000ef0, 0x00000ef9,
	0x00000f0c, 0x00000f1e, 0x00000f2f, 0x00000f45,
	0x00000f52, 0x00000f5d, 0x00000f6b, 0x00000f79,
	0x00000f8a, 0x00000f94, 0x00000f99, 0x00000fa1,
	0x00000fa8, 0x00000fb9, 0x00000fc2, 0x00000fc9,
	// Entry 100 - 11F
	0x00000fd0, 0x00000fd6, 0x00000fde, 0x00000fe6,
	0x00000fee, 0x00000ff4, 0x00000ffd, 0x00001005,
	0x0000100e, 0x00001012,
} // Size: 1088 bytes

const en_USData string = "" + // Size: 4114 bytes
	"\x02No such character\x02Cut to the chase\x02Not yet implemented, send c" +
	"ommand %[1]s instead\x02Query game role failed\x02No game role found, pl" +
	"ease send command /game_refresh_role to refresh\x02Please send me a priv" +
	"ate chat message\x02QR code login is being checked\x02Upsert user failed" +
	"\x02Fetch QR code failed\x02Generate QR code failed\x02Please scan the Q" +
	"R code with the miyoushe App\x02What are you looking for, it does not ex" +
	"ist\x02Monday\x02Thursday\x02Tuesday\x02Friday\x02Wednesday\x02Saturday" +
	"\x02Login failed or QR code expired, please try again\x02Game token pars" +
	"e failed, please try again\x02Cookie token fetch failed, please try agai" +
	"n\x02stoken fetch failed, please try again\x02Upsert game account failed" +
	"\x02fetch game record failed, please try again\x02The account is not yet" +
	" bound to any game, please make sure the account of scanning code is cor" +
	"rect\x02The account has not been bound to Genshin Impact, please confirm" +
	" that the account is correct\x02Upsert game roles failed\x02Upsert game " +
	"roles attribute failed\x02Authentication successfully\x02Pyro\x02Hydro" +
	"\x02Anemo\x02Electro\x02Dendro\x02Cryo\x02Geo\x02A Thousand Floating Dre" +
	"ams\x02Akuoumaru\x02Albedo\x02Alhaitham\x02Alley Hunter\x02Aloy\x02Amber" +
	"\x02Amenoma Kageuchi\x02Amos Bow\x02Apprentices Notes\x02Aqua Simulacra" +
	"\x02Aquila Favonia\x02Arataki Itto\x02Baizhu\x02Barbara\x02Beacon of the" +
	" Reed Sea\x02Beginners Protector\x02Beidou\x02Bennett\x02Black Tassel" +
	"\x02Blackcliff Agate\x02Blackcliff Longsword\x02Blackcliff Pole\x02Black" +
	"cliff Slasher\x02Blackcliff Warbow\x02Bloodtainted Greatsword\x02Calamit" +
	"y Queller\x02Candace\x02Chongyun\x02Cinnabar Spindle\x02Collei\x02Compou" +
	"nd Bow\x02Cool Steel\x02Crescent Pike\x02Cyno\x02Dark Iron Sword\x02Deat" +
	"hmatch\x02Debate Club\x02Dehya\x02Diluc\x02Diona\x02Dodoco Tales\x02Dori" +
	"\x02Dragons Bane\x02Dragonspine Spear\x02Dull Blade\x02Elegy for the End" +
	"\x02Emerald Orb\x02End of the Line\x02Engulfing Lightning\x02Eula\x02Eve" +
	"rlasting Moonglow\x02Eye of Perception\x02Fading Twilight\x02Faruzan\x02" +
	"Favonius Codex\x02Favonius Greatsword\x02Favonius Lance\x02Favonius Swor" +
	"d\x02Favonius Warbow\x02Ferrous Shadow\x02Festering Desire\x02Fillet Bla" +
	"de\x02Fischl\x02Forest Regalia\x02Freedom-Sworn\x02Frostbearer\x02Fruit " +
	"of Fulfillment\x02Ganyu\x02Gorou\x02Hakushin Ring\x02Halberd\x02Hamayumi" +
	"\x02Haran Geppaku Futsu\x02Harbinger of Dawn\x02Hu Tao\x02Hunters Bow" +
	"\x02Hunters Path\x02Iron Point\x02Iron Sting\x02Jadefalls Splendor\x02Je" +
	"an\x02Kaedehara Kazuha\x02Kaeya\x02Kagotsurube Isshin\x02Kaguras Verity" +
	"\x02Kamisato Ayaka\x02Kamisato Ayato\x02Katsuragikiri Nagamasa\x02Kaveh" +
	"\x02Keqing\x02Key of Khaj Nisut\x02Kings Squire\x02Kirara\x02Kitain Cros" +
	"s Spear\x02Klee\x02Kujou Sara\x02Kuki Shinobu\x02Layla\x02Light of Folia" +
	"r Incision\x02Lions Roar\x02Lisa\x02Lithic Blade\x02Lithic Spear\x02Lost" +
	" Prayer to the Sacred Winds\x02Luxurious Sea Lord\x02Magic Guide\x02Mail" +
	"ed Flower\x02Makhaira Aquamarine\x02Mappa Mare\x02Memory of Dust\x02Mess" +
	"enger\x02Mika\x02Missive Windspear\x02Mistsplitter Reforged\x02Mitternac" +
	"hts Waltz\x02Mona\x02Moonpiercer\x02Mouuns Moon\x02Nahida\x02Nilou\x02Ni" +
	"ngguang\x02Noelle\x02Oathsworn Eye\x02Otherworldly Story\x02Pocket Grimo" +
	"ire\x02Polar Star\x02Predator\x02Primordial Jade Cutter\x02Primordial Ja" +
	"de Winged Spear\x02Prototype Amber\x02Prototype Archaic\x02Prototype Cre" +
	"scent\x02Prototype Rancour\x02Prototype Starglitter\x02Qiqi\x02Raiden Sh" +
	"ogun\x02Rainslasher\x02Raven Bow\x02Razor\x02Recurve Bow\x02Redhorn Ston" +
	"ethresher\x02Rosaria\x02Royal Bow\x02Royal Greatsword\x02Royal Grimoire" +
	"\x02Royal Longsword\x02Royal Spear\x02Rust\x02Sacrificial Bow\x02Sacrifi" +
	"cial Fragments\x02Sacrificial Greatsword\x02Sacrificial Sword\x02Sangono" +
	"miya Kokomi\x02Sapwood Blade\x02Sayu\x02Seasoned Hunters Bow\x02Serpent " +
	"Spine\x02Sharpshooters Oath\x02Shenhe\x02Shikanoin Heizou\x02Silver Swor" +
	"d\x02Skyrider Greatsword\x02Skyrider Sword\x02Skyward Atlas\x02Skyward B" +
	"lade\x02Skyward Harp\x02Skyward Pride\x02Skyward Spine\x02Slingshot\x02S" +
	"now Tombed Starsilver\x02Solar Pearl\x02Song of Broken Pines\x02Staff of" +
	" Homa\x02Staff of the Scarlet Sands\x02Sucrose\x02Summit Shaper\x02Sword" +
	" of Descension\x02Tartaglia\x02The Alley Flash\x02The Bell\x02The Black " +
	"Sword\x02The Catch\x02The Flute\x02The Stringless\x02The Unforged\x02The" +
	" Viridescent Hunt\x02The Widsith\x02Thoma\x02Thrilling Tales of Dragon S" +
	"layers\x02Thundering Pulse\x02Tighnari\x02Toukabou Shigure\x02Traveler A" +
	"nemo\x02Traveler Dendro\x02Traveler Electro\x02Traveler Geo\x02Travelers" +
	" Handy Sword\x02Tulaytullahs Remembrance\x02Twin Nephrite\x02Venti\x02Vo" +
	"rtex Vanquisher\x02Wanderer\x02Wandering Evenstar\x02Waster Greatsword" +
	"\x02Wavebreakers Fin\x02White Iron Greatsword\x02White Tassel\x02Whitebl" +
	"ind\x02Windblume Ode\x02Wine and Song\x02Wolfs Gravestone\x02Xiangling" +
	"\x02Xiao\x02Xingqiu\x02Xinyan\x02Xiphos Moonlight\x02Yae Miko\x02Yanfei" +
	"\x02Yaoyao\x02Yelan\x02Yoimiya\x02Yun Jin\x02Zhongli\x02Sword\x02Claymor" +
	"e\x02Polearm\x02Catalyst\x02Bow"

var zh_HansIndex = []uint32{ // 266 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000d, 0x0000001a, 0x00000043,
	0x0000005c, 0x000000a4, 0x000000ba, 0x000000d9,
	0x000000ec, 0x00000102, 0x00000118, 0x0000013c,
	0x00000157, 0x0000015e, 0x00000165, 0x0000016c,
	0x00000173, 0x0000017a, 0x00000181, 0x000001ac,
	0x000001d1, 0x000001f8, 0x00000218, 0x00000231,
	0x00000256, 0x00000299, 0x000002d6, 0x000002ef,
	0x0000030e, 0x0000031b, 0x0000031f, 0x00000323,
	// Entry 20 - 3F
	0x00000327, 0x0000032b, 0x0000032f, 0x00000333,
	0x00000337, 0x00000344, 0x0000034e, 0x00000358,
	0x00000365, 0x00000372, 0x0000037c, 0x00000383,
	0x00000393, 0x000003a3, 0x000003b0, 0x000003b7,
	0x000003c1, 0x000003ce, 0x000003d5, 0x000003df,
	0x000003ec, 0x000003f9, 0x00000400, 0x0000040a,
	0x00000414, 0x00000421, 0x0000042e, 0x0000043b,
	0x00000448, 0x00000455, 0x00000468, 0x0000046f,
	// Entry 40 - 5F
	0x00000479, 0x00000480, 0x00000490, 0x00000497,
	0x000004a1, 0x000004a8, 0x000004b2, 0x000004b9,
	0x000004c3, 0x000004d0, 0x000004dd, 0x000004e7,
	0x000004f1, 0x000004fb, 0x0000050e, 0x00000515,
	0x00000522, 0x0000052f, 0x00000539, 0x0000054c,
	0x00000559, 0x00000560, 0x00000570, 0x00000577,
	0x00000584, 0x0000058b, 0x00000592, 0x0000059c,
	0x000005a9, 0x000005b6, 0x000005c3, 0x000005cd,
	// Entry 60 - 7F
	0x000005da, 0x000005e7, 0x000005f4, 0x00000601,
	0x0000060b, 0x00000618, 0x0000062b, 0x00000638,
	0x00000645, 0x0000064c, 0x00000653, 0x00000660,
	0x00000667, 0x00000674, 0x00000687, 0x00000694,
	0x0000069b, 0x000006a2, 0x000006af, 0x000006b9,
	0x000006c3, 0x000006d0, 0x000006d4, 0x000006e1,
	0x000006e8, 0x000006f8, 0x00000708, 0x00000715,
	0x00000722, 0x00000732, 0x00000739, 0x00000740,
	// Entry 80 - 9F
	0x0000074d, 0x0000075a, 0x00000764, 0x00000777,
	0x0000077e, 0x0000078b, 0x00000795, 0x0000079f,
	0x000007ac, 0x000007b9, 0x000007c0, 0x000007cd,
	0x000007da, 0x000007e7, 0x000007f4, 0x00000801,
	0x0000080e, 0x00000821, 0x00000834, 0x00000841,
	0x00000848, 0x0000084f, 0x0000085c, 0x0000086c,
	0x0000087c, 0x00000883, 0x0000088d, 0x0000089a,
	0x000008a4, 0x000008ab, 0x000008b2, 0x000008bc,
	// Entry A0 - BF
	0x000008cc, 0x000008dc, 0x000008ec, 0x000008f9,
	0x00000903, 0x00000910, 0x0000091a, 0x00000927,
	0x00000934, 0x00000941, 0x0000094e, 0x0000095b,
	0x00000962, 0x0000096f, 0x00000976, 0x00000980,
	0x00000987, 0x00000991, 0x000009a1, 0x000009ae,
	0x000009bb, 0x000009c8, 0x000009d8, 0x000009e5,
	0x000009f2, 0x000009f9, 0x00000a03, 0x00000a10,
	0x00000a1d, 0x00000a27, 0x00000a37, 0x00000a41,
	// Entry C0 - DF
	0x00000a48, 0x00000a58, 0x00000a62, 0x00000a72,
	0x00000a79, 0x00000a89, 0x00000a90, 0x00000aa0,
	0x00000aad, 0x00000aba, 0x00000ac7, 0x00000ad4,
	0x00000ae1, 0x00000aee, 0x00000af5, 0x00000b05,
	0x00000b12, 0x00000b25, 0x00000b32, 0x00000b3f,
	0x00000b46, 0x00000b53, 0x00000b60, 0x00000b6d,
	0x00000b7a, 0x00000b81, 0x00000b88, 0x00000b95,
	0x00000b9c, 0x00000ba3, 0x00000bb0, 0x00000bbd,
	// Entry E0 - FF
	0x00000bca, 0x00000bd1, 0x00000be1, 0x00000bf1,
	0x00000bfb, 0x00000c0b, 0x00000c1a, 0x00000c29,
	0x00000c38, 0x00000c47, 0x00000c51, 0x00000c67,
	0x00000c74, 0x00000c7b, 0x00000c88, 0x00000c92,
	0x00000ca2, 0x00000caf, 0x00000cbc, 0x00000cc9,
	0x00000cd3, 0x00000cdd, 0x00000cea, 0x00000cfd,
	0x00000d0a, 0x00000d11, 0x00000d15, 0x00000d1c,
	0x00000d23, 0x00000d36, 0x00000d43, 0x00000d4a,
	// Entry 100 - 11F
	0x00000d51, 0x00000d58, 0x00000d5f, 0x00000d66,
	0x00000d6d, 0x00000d77, 0x00000d81, 0x00000d8e,
	0x00000d95, 0x00000d99,
} // Size: 1088 bytes

const zh_HansData string = "" + // Size: 3481 bytes
	"\x02查无此人\x02斩尽牛杂\x02尚未实现，发送命令 %[1]s 代替\x02查询游戏角色失败\x02没有找到游戏角色，请发送命令 /ga" +
	"me_refresh_role 来刷新\x02请发送私聊信息\x02二维码登录正在检查中\x02保存用户失败\x02获取二维码失败\x02生成二" +
	"维码失败\x02请用米游社 APP 扫描二维码\x02你找啥呢, 不存在的\x02周一\x02周四\x02周二\x02周五\x02周三" +
	"\x02周六\x02登录失败或二维码过期，请重试\x02游戏令牌解析失败，请重试\x02获取 Cookie 令牌失败，请重试\x02SToken" +
	" 获取失败，请重试\x02保存游戏账户失败\x02获取游戏记录失败，请重试\x02该账号尚未绑定任何游戏，请确认扫码的账号无误\x02该账号尚未" +
	"绑定原神，请确认扫码的账号无误\x02更新游戏角色失败\x02更新游戏角色属性失败\x02认证成功\x02火\x02水\x02风\x02雷" +
	"\x02草\x02冰\x02岩\x02千夜浮梦\x02恶王丸\x02阿贝多\x02艾尔海森\x02暗巷猎手\x02埃洛伊\x02安柏\x02天目" +
	"影打刀\x02阿莫斯之弓\x02学徒笔记\x02若水\x02风鹰剑\x02荒泷一斗\x02白术\x02芭芭拉\x02苇海信标\x02新手长枪" +
	"\x02北斗\x02班尼特\x02黑缨枪\x02黑岩绯玉\x02黑岩长剑\x02黑岩刺枪\x02黑岩斩刀\x02黑岩战弓\x02沐浴龙血的剑" +
	"\x02息灾\x02坎蒂丝\x02重云\x02辰砂之纺锤\x02柯莱\x02钢轮弓\x02冷刃\x02流月针\x02赛诺\x02暗铁剑\x02决" +
	"斗之枪\x02以理服人\x02迪希雅\x02迪卢克\x02迪奥娜\x02嘟嘟可故事集\x02多莉\x02匣里灭辰\x02龙脊长枪\x02无锋" +
	"剑\x02终末嗟叹之诗\x02翡玉法球\x02竭泽\x02薙草之稻光\x02优菈\x02不灭月华\x02昭心\x02落霞\x02珐露珊" +
	"\x02西风秘典\x02西风大剑\x02西风长枪\x02西风剑\x02西风猎弓\x02铁影阔剑\x02腐殖之剑\x02吃虎鱼刀\x02菲谢尔" +
	"\x02森林王器\x02苍古自由之誓\x02忍冬之果\x02盈满之实\x02甘雨\x02五郎\x02白辰之环\x02钺矛\x02破魔之弓\x02" +
	"波乱月白经津\x02黎明神剑\x02胡桃\x02猎弓\x02猎人之径\x02铁尖枪\x02铁蜂刺\x02碧落之珑\x02琴\x02枫原万叶" +
	"\x02凯亚\x02笼钓瓶一心\x02神乐之真意\x02神里绫华\x02神里绫人\x02桂木斩长正\x02卡维\x02刻晴\x02圣显之钥" +
	"\x02王下近侍\x02绮良良\x02喜多院十文字\x02可莉\x02九条裟罗\x02久岐忍\x02莱依拉\x02裁叶萃光\x02匣里龙吟" +
	"\x02丽莎\x02千岩古剑\x02千岩长枪\x02四风原典\x02衔珠海皇\x02魔导绪论\x02饰铁之花\x02玛海菈的水色\x02万国诸海" +
	"图谱\x02尘世之锁\x02信使\x02米卡\x02风信之锋\x02雾切之回光\x02幽夜华尔兹\x02莫娜\x02贯月矢\x02曚云之月" +
	"\x02纳西妲\x02妮露\x02凝光\x02诺艾尔\x02证誓之明瞳\x02异世界行记\x02口袋魔导书\x02冬极白星\x02掠食者\x02" +
	"磐岩结绿\x02和璞鸢\x02试作金珀\x02试作古华\x02试作澹月\x02试作斩岩\x02试作星镰\x02七七\x02雷电将军\x02雨" +
	"裁\x02鸦羽弓\x02雷泽\x02反曲弓\x02赤角石溃杵\x02罗莎莉亚\x02宗室长弓\x02宗室大剑\x02宗室秘法录\x02宗室长" +
	"剑\x02宗室猎枪\x02弓藏\x02祭礼弓\x02祭礼残章\x02祭礼大剑\x02祭礼剑\x02珊瑚宫心海\x02原木刀\x02早柚" +
	"\x02历练的猎弓\x02螭骨剑\x02神射手之誓\x02申鹤\x02鹿野院平藏\x02银剑\x02飞天大御剑\x02飞天御剑\x02天空之卷" +
	"\x02天空之刃\x02天空之翼\x02天空之傲\x02天空之脊\x02弹弓\x02雪葬的星银\x02匣里日月\x02松籁响起之时\x02护摩之" +
	"杖\x02赤沙之杖\x02砂糖\x02斫峰之刃\x02降临之剑\x02达达利亚\x02暗巷闪光\x02钟剑\x02黑剑\x02「渔获」" +
	"\x02笛剑\x02绝弦\x02无工之剑\x02苍翠猎弓\x02流浪乐章\x02托马\x02讨龙英杰谭\x02飞雷之弦振\x02提纳里\x02东" +
	"花坊时雨\x02旅行者(风)\x02旅行者(草)\x02旅行者(雷)\x02旅行者(岩)\x02旅行剑\x02图莱杜拉的回忆\x02甲级宝珏" +
	"\x02温迪\x02贯虹之槊\x02流浪者\x02流浪的晚星\x02训练大剑\x02断浪长鳍\x02白铁大剑\x02白缨枪\x02白影剑\x02" +
	"风花之颂\x02暗巷的酒与诗\x02狼的末路\x02香菱\x02魈\x02行秋\x02辛焱\x02西福斯的月光\x02八重神子\x02烟绯" +
	"\x02瑶瑶\x02夜兰\x02宵宫\x02云堇\x02钟离\x02单手剑\x02双手剑\x02长柄武器\x02法器\x02弓"

	// Total table size 9771 bytes (9KiB); checksum: F68C3209
