# app main config

telegram:
  token: XXX
  poll-duration: 10s
  debug: false
  verbose: false

proxy:
  # socks5://127.0.0.1:1090
  telegram: ""
  mihoyo: ""

admins: []

app:
  assets:
    base-url: https://test.s3.ap-northeast-1.amazonaws.com

db:
  type: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  dbname: keqing

cache:
  dir: tmp/cache
