# app main config

telegram:
  token: XXX
  poll-duration: 10s
  verbose: false

proxy: socks5://127.0.0.1:1090

admins: []

db:
  type: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  dbname: keqing
