# GitHub Action that uploads coverage reports for your repository to codecov.io
name: Codecov

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Codecov
      # You may pin to the exact commit or the version.
      # uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        
