// Code generated by running "go generate" DO NOT EDIT

package {{ .Package }}

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"

	_ "github.com/lostsnow/keqing/pkg/i18n/catalog"
)

var p = message.NewPrinter(language.AmericanEnglish)

var (
	{{ range .Translations -}}
	_ = p.Sprintf("{{ . }}")
	{{ end }}
)
